using System.Text.Json.Nodes;

namespace Servyx.Infrastructure.Aws;

/// <summary>
/// The Lightsail objects this adapter reads, projected out of the API's JSON into ordinary records.
/// </summary>
/// <remarks>
/// <para>
/// <strong>Hand-projected for the same reason <c>Ec2Xml</c> is, over a different tree.</strong> Lightsail speaks
/// the AWS JSON 1.1 protocol rather than EC2's Query/XML protocol, so this file reads <see cref="JsonNode"/>
/// (specifically <see cref="JsonObject"/>/<see cref="JsonArray"/>) instead of <c>XElement</c> — but the reason
/// for hand-projecting rather than <c>System.Text.Json</c>'s attribute-based deserialisation is the same one:
/// the response schema is large and versioned, and this adapter only ever reads a handful of fields off it.
/// <see cref="JsonNode"/> is in the shared framework (no package reference), exactly as <c>XElement</c> is.
/// </para>
/// <para>
/// <strong>The one field worth calling out: <c>username</c>.</strong> EC2's <c>DescribeInstances</c> has no
/// equivalent field at all — an AMI's default login account is not discoverable from the API, which is why
/// <c>AwsEc2Provisioner</c> has to carry a constructor-supplied default that is right for some AMI families and
/// silently wrong for others. Lightsail's <c>Instance</c> object reports the blueprint's login username
/// directly, so <see cref="LightsailInstance.Username"/> is read from the provider's own answer rather than
/// guessed at construction time. See <c>AwsLightsailProvisioner</c>'s remarks for what this changes.
/// </para>
/// </remarks>
internal static class LightsailJson
{
    /// <summary>The text of a named property, or <see langword="null"/> when absent, not a string, or blank.</summary>
    internal static string? Text(JsonObject? obj, string property)
    {
        if (obj is null || !obj.TryGetPropertyValue(property, out var node) || node is null)
        {
            return null;
        }

        string? text;
        try
        {
            text = node.GetValue<string>();
        }
        catch (InvalidOperationException)
        {
            return null;
        }
        catch (FormatException)
        {
            return null;
        }

        return string.IsNullOrWhiteSpace(text) ? null : text;
    }

    /// <summary>A named property read as a Unix-epoch-seconds number, or <see langword="null"/> when absent or not numeric.</summary>
    internal static DateTimeOffset? UnixSeconds(JsonObject? obj, string property)
    {
        if (obj is null || !obj.TryGetPropertyValue(property, out var node) || node is null)
        {
            return null;
        }

        try
        {
            return DateTimeOffset.UnixEpoch.AddSeconds(node.GetValue<double>());
        }
        catch (InvalidOperationException)
        {
            return null;
        }
        catch (FormatException)
        {
            return null;
        }
    }

    /// <summary>Reads a Lightsail <c>tags</c> array (<c>[{"key":...,"value":...}]</c>) into an ordinal dictionary.</summary>
    /// <remarks>
    /// A key-only tag (Lightsail allows a tag with no value) reads as an empty string, matching how
    /// <c>Ec2Xml.Tags</c> treats a tag whose <c>&lt;value&gt;</c> element is empty. Servyx itself never writes a
    /// key-only tag — every canonical key carries a real value — so this branch only matters for a resource
    /// someone else tagged by hand.
    /// </remarks>
    internal static IReadOnlyDictionary<string, string> Tags(JsonArray? tags)
    {
        var result = new Dictionary<string, string>(StringComparer.Ordinal);

        if (tags is null)
        {
            return result;
        }

        foreach (var node in tags)
        {
            if (node is not JsonObject tag)
            {
                continue;
            }

            var key = Text(tag, "key");
            if (key is not null)
            {
                result[key] = Text(tag, "value") ?? string.Empty;
            }
        }

        return result;
    }
}

/// <summary>A Lightsail instance, as <c>GetInstance</c>/<c>GetInstances</c> describe it.</summary>
/// <param name="Name">
/// The instance's name — the identity Lightsail assigns it, chosen by the caller at <c>CreateInstances</c> time
/// rather than generated by the provider. This is also the identifier every other action (<c>GetInstance</c>,
/// <c>DeleteInstance</c>) keys on, so it is what this adapter stores as <c>ResourceHandle.ProviderResourceId</c>.
/// </param>
/// <param name="BlueprintId">The OS/application image the instance was created from.</param>
/// <param name="BundleId">The bundle (size/plan) the instance was created at. This is the priced dimension.</param>
/// <param name="StateName">The lifecycle state name, e.g. <c>pending</c>, <c>running</c>, <c>stopping</c>, <c>stopped</c>.</param>
/// <param name="PublicIpAddress">The public IPv4 address, if the instance has one yet.</param>
/// <param name="PrivateIpAddress">The private IPv4 address, if the instance has one yet.</param>
/// <param name="AvailabilityZone">The availability zone the instance was created in.</param>
/// <param name="Username">
/// The blueprint's default SSH login account, as Lightsail itself reports it — e.g. <c>ec2-user</c>,
/// <c>ubuntu</c>, <c>bitnami</c>. See the type remarks: EC2 has no equivalent field.
/// </param>
/// <param name="CreatedAt">When Lightsail reports the instance was created.</param>
/// <param name="Tags">The instance's tags, decoded from its <c>tags</c> array.</param>
internal sealed record LightsailInstance(
    string Name,
    string? BlueprintId,
    string? BundleId,
    string? StateName,
    string? PublicIpAddress,
    string? PrivateIpAddress,
    string? AvailabilityZone,
    string? Username,
    DateTimeOffset? CreatedAt,
    IReadOnlyDictionary<string, string> Tags)
{
    /// <summary>Projects one element of a <c>GetInstances</c> response's <c>instances</c> array, or the <c>instance</c> object <c>GetInstance</c> returns.</summary>
    internal static LightsailInstance? From(JsonObject? item)
    {
        var name = LightsailJson.Text(item, "name");
        if (name is null)
        {
            return null;
        }

        var location = item?["location"] as JsonObject;
        var state = item?["state"] as JsonObject;

        return new LightsailInstance(
            name,
            LightsailJson.Text(item, "blueprintId"),
            LightsailJson.Text(item, "bundleId"),
            LightsailJson.Text(state, "name"),
            LightsailJson.Text(item, "publicIpAddress"),
            LightsailJson.Text(item, "privateIpAddress"),
            LightsailJson.Text(location, "availabilityZone"),
            LightsailJson.Text(item, "username"),
            LightsailJson.UnixSeconds(item, "createdAt"),
            LightsailJson.Tags(item?["tags"] as JsonArray));
    }
}

/// <summary>
/// The Lightsail error type names this adapter distinguishes by. Unlike EC2's per-situation codes
/// (<c>InvalidInstanceID.NotFound</c>), Lightsail answers every "no such resource" case — an unknown instance
/// name for <c>GetInstance</c> or <c>DeleteInstance</c> alike — with the same generic <c>NotFoundException</c>,
/// so there is exactly one code to check rather than one per action.
/// </summary>
internal static class LightsailErrorCodes
{
    /// <summary>Lightsail could not find the named resource. HTTP 400, not 404.</summary>
    internal const string NotFound = "NotFoundException";
}
