// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace Servyx.E2E.Bdd.Tests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::Xunit.TraitAttribute("Category", "e2e")]
    [global::Xunit.TraitAttribute("Category", "dark")]
    public partial class ThemingFeature : object, global::Xunit.IClassFixture<ThemingFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "e2e",
                "dark"};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Theming", "  As an operator who prefers a dark interface, or whose OS is set to dark mode\r\n " +
                " I want every documented screen available as a dark-theme capture too\r\n  So the " +
                "user guide never shows only a light interface for an app that ships both", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "Theming.feature"
#line hidden
        
        public ThemingFeature(ThemingFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 21
  #line hidden
#line 22
    await testRunner.GivenAsync("Servyx is running against the demonstration host", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Theming.feature.ndjson", 28);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="The dashboard summarises the whole estate at a glance, in dark theme")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Theming")]
        [global::Xunit.TraitAttribute("Description", "The dashboard summarises the whole estate at a glance, in dark theme")]
        public async global::System.Threading.Tasks.Task TheDashboardSummarisesTheWholeEstateAtAGlanceInDarkTheme()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("The dashboard summarises the whole estate at a glance, in dark theme", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 25
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 21
  await this.FeatureBackgroundAsync();
#line hidden
#line 26
    await testRunner.WhenAsync("I open the dashboard", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 27
    await testRunner.ThenAsync("the page is in \"dark\" theme", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 28
    await testRunner.AndAsync("I capture the screen as \"dashboard-overview-dark\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="The server list shows where each server lives and how to reach it, in dark theme")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Theming")]
        [global::Xunit.TraitAttribute("Description", "The server list shows where each server lives and how to reach it, in dark theme")]
        public async global::System.Threading.Tasks.Task TheServerListShowsWhereEachServerLivesAndHowToReachItInDarkTheme()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("The server list shows where each server lives and how to reach it, in dark theme", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 31
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 21
  await this.FeatureBackgroundAsync();
#line hidden
#line 32
    await testRunner.WhenAsync("I open the servers list", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 33
    await testRunner.ThenAsync("the page is in \"dark\" theme", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 34
    await testRunner.AndAsync("I capture the screen as \"servers-list-dark\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="A server adopted over ssh+docker is listed alongside the local one, in dark theme" +
            "")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Theming")]
        [global::Xunit.TraitAttribute("Description", "A server adopted over ssh+docker is listed alongside the local one, in dark theme" +
            "")]
        public async global::System.Threading.Tasks.Task AServerAdoptedOverSshDockerIsListedAlongsideTheLocalOneInDarkTheme()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A server adopted over ssh+docker is listed alongside the local one, in dark theme" +
                    "", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 37
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 21
  await this.FeatureBackgroundAsync();
#line hidden
#line 38
    await testRunner.WhenAsync("I open the servers list", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 39
    await testRunner.ThenAsync("the page is in \"dark\" theme", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 40
    await testRunner.AndAsync("I capture the screen as \"servers-list-remote-host-dark\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="The remote server\'s Overview tab shows which ports actually reach the host, in da" +
            "rk theme")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Theming")]
        [global::Xunit.TraitAttribute("Description", "The remote server\'s Overview tab shows which ports actually reach the host, in da" +
            "rk theme")]
        public async global::System.Threading.Tasks.Task TheRemoteServersOverviewTabShowsWhichPortsActuallyReachTheHostInDarkTheme()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("The remote server\'s Overview tab shows which ports actually reach the host, in da" +
                    "rk theme", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 43
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 21
  await this.FeatureBackgroundAsync();
#line hidden
#line 44
    await testRunner.WhenAsync("I open the server detail page with id \"example-remote-palworld\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 45
    await testRunner.ThenAsync("the page is in \"dark\" theme", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 46
    await testRunner.AndAsync("I capture the screen as \"remote-server-overview-dark\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="The remote server\'s unhealthy badge explains the Palworld healthcheck false negat" +
            "ive, in dark theme")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Theming")]
        [global::Xunit.TraitAttribute("Description", "The remote server\'s unhealthy badge explains the Palworld healthcheck false negat" +
            "ive, in dark theme")]
        public async global::System.Threading.Tasks.Task TheRemoteServersUnhealthyBadgeExplainsThePalworldHealthcheckFalseNegativeInDarkTheme()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("The remote server\'s unhealthy badge explains the Palworld healthcheck false negat" +
                    "ive, in dark theme", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 49
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 21
  await this.FeatureBackgroundAsync();
#line hidden
#line 50
    await testRunner.WhenAsync("I open the server detail page with id \"example-remote-palworld\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 51
    await testRunner.ThenAsync("the page is in \"dark\" theme", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 52
    await testRunner.AndAsync("I capture the screen as \"remote-server-health-explanation-dark\", focused on the s" +
                        "tatus card", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="The run state and container health of a server are reported as separate indicator" +
            "s, in dark theme")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Theming")]
        [global::Xunit.TraitAttribute("Description", "The run state and container health of a server are reported as separate indicator" +
            "s, in dark theme")]
        public async global::System.Threading.Tasks.Task TheRunStateAndContainerHealthOfAServerAreReportedAsSeparateIndicatorsInDarkTheme()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("The run state and container health of a server are reported as separate indicator" +
                    "s, in dark theme", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 55
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 21
  await this.FeatureBackgroundAsync();
#line hidden
#line 56
    await testRunner.WhenAsync("I open the server detail page for \"Palygondwanaland\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 57
    await testRunner.ThenAsync("the page is in \"dark\" theme", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 58
    await testRunner.AndAsync("I capture the screen as \"server-overview-dark\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Every power action is present but disabled while Servyx is read-only, in dark the" +
            "me")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Theming")]
        [global::Xunit.TraitAttribute("Description", "Every power action is present but disabled while Servyx is read-only, in dark the" +
            "me")]
        public async global::System.Threading.Tasks.Task EveryPowerActionIsPresentButDisabledWhileServyxIsRead_OnlyInDarkTheme()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Every power action is present but disabled while Servyx is read-only, in dark the" +
                    "me", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 61
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 21
  await this.FeatureBackgroundAsync();
#line hidden
#line 62
    await testRunner.WhenAsync("I open the server detail page for \"Palygondwanaland\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 63
    await testRunner.ThenAsync("the page is in \"dark\" theme", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 64
    await testRunner.AndAsync("I capture the screen as \"control-tier-read-only-dark\", focused on the power contr" +
                        "ols", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="The console shows timestamped log lines with a warning highlighted, in dark theme" +
            "")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Theming")]
        [global::Xunit.TraitAttribute("Description", "The console shows timestamped log lines with a warning highlighted, in dark theme" +
            "")]
        public async global::System.Threading.Tasks.Task TheConsoleShowsTimestampedLogLinesWithAWarningHighlightedInDarkTheme()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "7";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("The console shows timestamped log lines with a warning highlighted, in dark theme" +
                    "", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 67
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 21
  await this.FeatureBackgroundAsync();
#line hidden
#line 68
    await testRunner.WhenAsync("I open the server detail page for \"Palygondwanaland\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 69
    await testRunner.AndAsync("I open the \"Console\" tab", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 70
    await testRunner.ThenAsync("the page is in \"dark\" theme", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 71
    await testRunner.AndAsync("I capture the screen as \"server-console-dark\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="A server with no RCON control channel configured says so plainly on its Console t" +
            "ab, in dark theme")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Theming")]
        [global::Xunit.TraitAttribute("Description", "A server with no RCON control channel configured says so plainly on its Console t" +
            "ab, in dark theme")]
        public async global::System.Threading.Tasks.Task AServerWithNoRCONControlChannelConfiguredSaysSoPlainlyOnItsConsoleTabInDarkTheme()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "8";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A server with no RCON control channel configured says so plainly on its Console t" +
                    "ab, in dark theme", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 74
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 21
  await this.FeatureBackgroundAsync();
#line hidden
#line 75
    await testRunner.WhenAsync("I open the server detail page for \"Palygondwanaland\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 76
    await testRunner.AndAsync("I open the \"Console\" tab", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 77
    await testRunner.ThenAsync("the page is in \"dark\" theme", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 78
    await testRunner.AndAsync("I capture the screen as \"console-no-rcon-channel-dark\", focused on the command pa" +
                        "nel", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Saves show the world id, level file size, and per-player saves, in dark theme")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Theming")]
        [global::Xunit.TraitAttribute("Description", "Saves show the world id, level file size, and per-player saves, in dark theme")]
        public async global::System.Threading.Tasks.Task SavesShowTheWorldIdLevelFileSizeAndPer_PlayerSavesInDarkTheme()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "9";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Saves show the world id, level file size, and per-player saves, in dark theme", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 81
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 21
  await this.FeatureBackgroundAsync();
#line hidden
#line 82
    await testRunner.WhenAsync("I open the server detail page for \"Palygondwanaland\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 83
    await testRunner.AndAsync("I open the \"Saves\" tab", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 84
    await testRunner.ThenAsync("the page is in \"dark\" theme", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 85
    await testRunner.AndAsync("I capture the screen as \"server-saves-dark\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="A server\'s own backups are labelled foreign with no destructive control present, " +
            "in dark theme")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Theming")]
        [global::Xunit.TraitAttribute("Description", "A server\'s own backups are labelled foreign with no destructive control present, " +
            "in dark theme")]
        public async global::System.Threading.Tasks.Task AServersOwnBackupsAreLabelledForeignWithNoDestructiveControlPresentInDarkTheme()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "10";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A server\'s own backups are labelled foreign with no destructive control present, " +
                    "in dark theme", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 88
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 21
  await this.FeatureBackgroundAsync();
#line hidden
#line 89
    await testRunner.WhenAsync("I open the server detail page for \"Palygondwanaland\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 90
    await testRunner.AndAsync("I open the \"Backups\" tab", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 91
    await testRunner.ThenAsync("the page is in \"dark\" theme", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 92
    await testRunner.AndAsync("I capture the screen as \"server-backups-foreign-dark\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="The estate-wide backups page lists every archive across every server, in dark the" +
            "me")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Theming")]
        [global::Xunit.TraitAttribute("Description", "The estate-wide backups page lists every archive across every server, in dark the" +
            "me")]
        public async global::System.Threading.Tasks.Task TheEstate_WideBackupsPageListsEveryArchiveAcrossEveryServerInDarkTheme()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "11";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("The estate-wide backups page lists every archive across every server, in dark the" +
                    "me", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 95
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 21
  await this.FeatureBackgroundAsync();
#line hidden
#line 96
    await testRunner.WhenAsync("I open the backups overview page", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 97
    await testRunner.ThenAsync("the page is in \"dark\" theme", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 98
    await testRunner.AndAsync("I capture the screen as \"backups-overview-dark\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="A setting shows its four tracked values and is flagged as drifted, in dark theme")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Theming")]
        [global::Xunit.TraitAttribute("Description", "A setting shows its four tracked values and is flagged as drifted, in dark theme")]
        public async global::System.Threading.Tasks.Task ASettingShowsItsFourTrackedValuesAndIsFlaggedAsDriftedInDarkTheme()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "12";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A setting shows its four tracked values and is flagged as drifted, in dark theme", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 101
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 21
  await this.FeatureBackgroundAsync();
#line hidden
#line 102
    await testRunner.WhenAsync("I open the server detail page for \"Palygondwanaland\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 103
    await testRunner.AndAsync("I open the \"Settings\" tab", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 104
    await testRunner.ThenAsync("the page is in \"dark\" theme", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 105
    await testRunner.AndAsync("I capture the screen as \"settings-four-columns-dark\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="A secret setting is masked rather than shown in the clear, in dark theme")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Theming")]
        [global::Xunit.TraitAttribute("Description", "A secret setting is masked rather than shown in the clear, in dark theme")]
        public async global::System.Threading.Tasks.Task ASecretSettingIsMaskedRatherThanShownInTheClearInDarkTheme()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "13";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A secret setting is masked rather than shown in the clear, in dark theme", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 108
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 21
  await this.FeatureBackgroundAsync();
#line hidden
#line 109
    await testRunner.WhenAsync("I open the server detail page for \"Palygondwanaland\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 110
    await testRunner.AndAsync("I open the \"Settings\" tab", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 111
    await testRunner.ThenAsync("the page is in \"dark\" theme", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 112
    await testRunner.AndAsync("I capture the screen as \"settings-secret-masking-dark\", focused on the masked set" +
                        "ting row", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="The top bar\'s connection status reports the transport\'s own probe detail, in dark" +
            " theme")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Theming")]
        [global::Xunit.TraitAttribute("Description", "The top bar\'s connection status reports the transport\'s own probe detail, in dark" +
            " theme")]
        public async global::System.Threading.Tasks.Task TheTopBarsConnectionStatusReportsTheTransportsOwnProbeDetailInDarkTheme()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "14";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("The top bar\'s connection status reports the transport\'s own probe detail, in dark" +
                    " theme", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 115
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 21
  await this.FeatureBackgroundAsync();
#line hidden
#line 116
    await testRunner.WhenAsync("I open the dashboard", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 117
    await testRunner.ThenAsync("the page is in \"dark\" theme", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 118
    await testRunner.AndAsync("I capture the screen as \"connection-status-healthy-dark\", focused on the connecti" +
                        "on status", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="The bundled game definition lists multiple deployment profiles, in dark theme")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Theming")]
        [global::Xunit.TraitAttribute("Description", "The bundled game definition lists multiple deployment profiles, in dark theme")]
        public async global::System.Threading.Tasks.Task TheBundledGameDefinitionListsMultipleDeploymentProfilesInDarkTheme()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "15";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("The bundled game definition lists multiple deployment profiles, in dark theme", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 121
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 21
  await this.FeatureBackgroundAsync();
#line hidden
#line 122
    await testRunner.WhenAsync("I open the games page", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 123
    await testRunner.ThenAsync("the page is in \"dark\" theme", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 124
    await testRunner.AndAsync("I capture the screen as \"games-catalogue-dark\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="The Audit page requires an authenticated Admin and lists the accountability trail" +
            ", in dark theme")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Theming")]
        [global::Xunit.TraitAttribute("Description", "The Audit page requires an authenticated Admin and lists the accountability trail" +
            ", in dark theme")]
        public async global::System.Threading.Tasks.Task TheAuditPageRequiresAnAuthenticatedAdminAndListsTheAccountabilityTrailInDarkTheme()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "16";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("The Audit page requires an authenticated Admin and lists the accountability trail" +
                    ", in dark theme", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 128
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 21
  await this.FeatureBackgroundAsync();
#line hidden
#line 129
    await testRunner.GivenAsync("I am signed in as an administrator", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 130
    await testRunner.WhenAsync("I open the audit page", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 131
    await testRunner.ThenAsync("the page is in \"dark\" theme", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 132
    await testRunner.AndAsync("I capture the screen as \"audit-page-dark\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="The provisioning gate names its own configuration key and warns when authenticati" +
            "on is off, in dark theme")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Theming")]
        [global::Xunit.TraitAttribute("Description", "The provisioning gate names its own configuration key and warns when authenticati" +
            "on is off, in dark theme")]
        public async global::System.Threading.Tasks.Task TheProvisioningGateNamesItsOwnConfigurationKeyAndWarnsWhenAuthenticationIsOffInDarkTheme()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "17";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("The provisioning gate names its own configuration key and warns when authenticati" +
                    "on is off, in dark theme", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 135
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 21
  await this.FeatureBackgroundAsync();
#line hidden
#line 136
    await testRunner.WhenAsync("I open the deploy page", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 137
    await testRunner.ThenAsync("the page is in \"dark\" theme", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 138
    await testRunner.AndAsync("I capture the screen as \"provisioning-gate-closed-dark\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="PreviewOnly renders the stop-escalation ladder and offers no control at all, in d" +
            "ark theme")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Theming")]
        [global::Xunit.TraitAttribute("Description", "PreviewOnly renders the stop-escalation ladder and offers no control at all, in d" +
            "ark theme")]
        [global::Xunit.TraitAttribute("Category", "write-enabled-host")]
        public async global::System.Threading.Tasks.Task PreviewOnlyRendersTheStop_EscalationLadderAndOffersNoControlAtAllInDarkTheme()
        {
            string[] tagsOfScenario = new string[] {
                    "write-enabled-host"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "18";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("PreviewOnly renders the stop-escalation ladder and offers no control at all, in d" +
                    "ark theme", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 142
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 21
  await this.FeatureBackgroundAsync();
#line hidden
#line 143
    await testRunner.GivenAsync("Servyx is running with provisioning enabled and per-server write grants", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 144
    await testRunner.WhenAsync("I open the server detail page for \"Palygondwanaland\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 145
    await testRunner.ThenAsync("the page is in \"dark\" theme", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 146
    await testRunner.AndAsync("I capture the screen as \"preview-only-stop-plan-dark\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="A fully-enabled server shows live, clickable Start, Restart, Stop, and Kill contr" +
            "ols, in dark theme")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Theming")]
        [global::Xunit.TraitAttribute("Description", "A fully-enabled server shows live, clickable Start, Restart, Stop, and Kill contr" +
            "ols, in dark theme")]
        [global::Xunit.TraitAttribute("Category", "write-enabled-host")]
        [global::Xunit.TraitAttribute("Category", "requires-docker")]
        public async global::System.Threading.Tasks.Task AFully_EnabledServerShowsLiveClickableStartRestartStopAndKillControlsInDarkTheme()
        {
            string[] tagsOfScenario = new string[] {
                    "write-enabled-host",
                    "requires-docker"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "19";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A fully-enabled server shows live, clickable Start, Restart, Stop, and Kill contr" +
                    "ols, in dark theme", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 150
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 21
  await this.FeatureBackgroundAsync();
#line hidden
#line 151
    await testRunner.GivenAsync("Servyx is running with provisioning enabled and per-server write grants", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 152
    await testRunner.WhenAsync("I open the server detail page for \"Example Remote Palworld\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 153
    await testRunner.ThenAsync("the page is in \"dark\" theme", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 154
    await testRunner.AndAsync("I capture the screen as \"lifecycle-controls-enabled-dark\", focused on the power c" +
                        "ontrols", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="The Mods placeholder explains mods are not supported for the bundled game, in dar" +
            "k theme")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Theming")]
        [global::Xunit.TraitAttribute("Description", "The Mods placeholder explains mods are not supported for the bundled game, in dar" +
            "k theme")]
        public async global::System.Threading.Tasks.Task TheModsPlaceholderExplainsModsAreNotSupportedForTheBundledGameInDarkTheme()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "20";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("The Mods placeholder explains mods are not supported for the bundled game, in dar" +
                    "k theme", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 159
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 21
  await this.FeatureBackgroundAsync();
#line hidden
#line 160
    await testRunner.WhenAsync("I open the mods page", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 161
    await testRunner.ThenAsync("the page is in \"dark\" theme", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 162
    await testRunner.AndAsync("I capture the screen as \"mods-dark\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="The Plugins placeholder explains the plugin SDK ships later, in dark theme")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Theming")]
        [global::Xunit.TraitAttribute("Description", "The Plugins placeholder explains the plugin SDK ships later, in dark theme")]
        public async global::System.Threading.Tasks.Task ThePluginsPlaceholderExplainsThePluginSDKShipsLaterInDarkTheme()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "21";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("The Plugins placeholder explains the plugin SDK ships later, in dark theme", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 164
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 21
  await this.FeatureBackgroundAsync();
#line hidden
#line 165
    await testRunner.WhenAsync("I open the plugins page", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 166
    await testRunner.ThenAsync("the page is in \"dark\" theme", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 167
    await testRunner.AndAsync("I capture the screen as \"plugins-dark\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="The Users page requires an authenticated Admin and lists accounts, in dark theme")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Theming")]
        [global::Xunit.TraitAttribute("Description", "The Users page requires an authenticated Admin and lists accounts, in dark theme")]
        public async global::System.Threading.Tasks.Task TheUsersPageRequiresAnAuthenticatedAdminAndListsAccountsInDarkTheme()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "22";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("The Users page requires an authenticated Admin and lists accounts, in dark theme", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 169
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 21
  await this.FeatureBackgroundAsync();
#line hidden
#line 170
    await testRunner.GivenAsync("I am signed in as an administrator", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 171
    await testRunner.WhenAsync("I open the users page", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 172
    await testRunner.ThenAsync("the page is in \"dark\" theme", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 173
    await testRunner.AndAsync("I capture the screen as \"users-dark\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="The application Settings placeholder explains there is nothing to configure yet, " +
            "in dark theme")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Theming")]
        [global::Xunit.TraitAttribute("Description", "The application Settings placeholder explains there is nothing to configure yet, " +
            "in dark theme")]
        public async global::System.Threading.Tasks.Task TheApplicationSettingsPlaceholderExplainsThereIsNothingToConfigureYetInDarkTheme()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "23";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("The application Settings placeholder explains there is nothing to configure yet, " +
                    "in dark theme", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 175
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 21
  await this.FeatureBackgroundAsync();
#line hidden
#line 176
    await testRunner.WhenAsync("I open the app settings page", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 177
    await testRunner.ThenAsync("the page is in \"dark\" theme", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 178
    await testRunner.AndAsync("I capture the screen as \"settings-dark\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="An unknown route renders the Not Found page, in dark theme")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Theming")]
        [global::Xunit.TraitAttribute("Description", "An unknown route renders the Not Found page, in dark theme")]
        public async global::System.Threading.Tasks.Task AnUnknownRouteRendersTheNotFoundPageInDarkTheme()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "24";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("An unknown route renders the Not Found page, in dark theme", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 180
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 21
  await this.FeatureBackgroundAsync();
#line hidden
#line 181
    await testRunner.WhenAsync("I open a page that does not exist", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 182
    await testRunner.ThenAsync("the page is in \"dark\" theme", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 183
    await testRunner.AndAsync("I capture the screen as \"not-found-dark\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="The Error page is directly routable and reports a request id, in dark theme")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Theming")]
        [global::Xunit.TraitAttribute("Description", "The Error page is directly routable and reports a request id, in dark theme")]
        public async global::System.Threading.Tasks.Task TheErrorPageIsDirectlyRoutableAndReportsARequestIdInDarkTheme()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "25";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("The Error page is directly routable and reports a request id, in dark theme", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 186
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 21
  await this.FeatureBackgroundAsync();
#line hidden
#line 187
    await testRunner.WhenAsync("I navigate directly to the error page", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 188
    await testRunner.ThenAsync("the page is in \"dark\" theme", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 189
    await testRunner.AndAsync("I capture the screen as \"error-page-dark\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await ThemingFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await ThemingFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
