// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Servyx.Infrastructure.Persistence;

#nullable disable

namespace Servyx.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ServyxDbContext))]
    [Migration("20260810032112_AddChangePlans")]
    partial class AddChangePlans
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Servyx.Domain.Entities.ChangePlanActionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("AppliedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ChangePlanId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ContainsSecrets")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FailureReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PostImageContent")
                        .HasColumnType("TEXT");

                    b.Property<string>("PostImageHash")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreImageContent")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreImageHash")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("RequiredCapabilities")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResolvedPath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Reversible")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("RevertedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("SurfaceId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("UnifiedDiff")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChangePlanId", "Ordinal")
                        .IsUnique();

                    b.ToTable("ChangePlanActions", (string)null);
                });

            modelBuilder.Entity("Servyx.Domain.Entities.ChangePlanRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("AppliedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("AppliedBy")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("BlockedJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConsequencesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("DefinitionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("DefinitionVersion")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("RevertedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RevertedBy")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("SurfaceHashesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ServerId");

                    b.HasIndex("Status");

                    b.ToTable("ChangePlans", (string)null);
                });

            modelBuilder.Entity("Servyx.Domain.Entities.Host", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConnectorId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderAccountId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderResourceId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProvisionedByJobId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConnectorId");

                    b.HasIndex("ProviderAccountId", "ProviderResourceId");

                    b.ToTable("Hosts", (string)null);
                });

            modelBuilder.Entity("Servyx.Domain.Entities.ProviderAccount", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CredentialUrns")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("CredentialUrnsJson");

                    b.Property<string>("DefaultRegion")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ScopeHint")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId");

                    b.ToTable("ProviderAccounts", (string)null);
                });

            modelBuilder.Entity("Servyx.Domain.Entities.Server", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AdoptionMode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContainerId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefinitionContentHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("GameDefinitionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("HostId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("WriteMode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("WriteModeChangedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("WriteModeChangedBy")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContainerId")
                        .IsUnique();

                    b.HasIndex("GameDefinitionId");

                    b.HasIndex("HostId");

                    b.ToTable("Servers", (string)null);
                });

            modelBuilder.Entity("Servyx.Domain.Entities.ServerSettingValue", b =>
                {
                    b.Property<Guid>("ServerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ServerId", "Key");

                    b.ToTable("ServerSettingValues", (string)null);
                });

            modelBuilder.Entity("Servyx.Infrastructure.Persistence.Entities.ProvisionedResourceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("HostId")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderResourceId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProvisionerId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ServerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("TagsJson");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("State");

                    b.HasIndex("ProvisionerId", "ProviderResourceId");

                    b.ToTable("ProvisionedResources", (string)null);
                });

            modelBuilder.Entity("Servyx.Infrastructure.Persistence.Entities.ServerDefinitionBindingRecord", b =>
                {
                    b.Property<string>("ServerId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("CandidateDefinitionIds")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("CandidateDefinitionIdsJson");

                    b.Property<string>("DefinitionContentHash")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("DefinitionId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("DefinitionSourceId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("DefinitionSourcePath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("ServerId");

                    b.HasIndex("State");

                    b.ToTable("ServerDefinitionBindings", (string)null);
                });

            modelBuilder.Entity("Servyx.Domain.Entities.ChangePlanActionRecord", b =>
                {
                    b.HasOne("Servyx.Domain.Entities.ChangePlanRecord", null)
                        .WithMany()
                        .HasForeignKey("ChangePlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Servyx.Domain.Entities.ChangePlanRecord", b =>
                {
                    b.HasOne("Servyx.Domain.Entities.Server", null)
                        .WithMany()
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Servyx.Domain.Entities.ServerSettingValue", b =>
                {
                    b.HasOne("Servyx.Domain.Entities.Server", null)
                        .WithMany()
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
