namespace Servyx.Domain.Configuration;

/// <summary>
/// The role a configuration surface plays. This is the central modeling decision in Servyx: every
/// configuration surface is one of these three, and the role determines whether Servyx may write to it
/// at all.
/// </summary>
public enum SurfaceRole
{
    /// <summary>Servyx may write to this surface; it is a genuine source of intent (e.g. <c>.env</c>).</summary>
    Authoritative,

    /// <summary>
    /// Generated by the workload itself at boot. Servyx reads this surface for drift detection only, and
    /// MUST NEVER write it — a write would be silently discarded or would fight the workload's own
    /// generator the next time it regenerates the surface. This exact failure mode is why users lose
    /// trust in control panels that do not model it, and why it is enforced structurally here rather than
    /// left to adapter discipline.
    /// </summary>
    Derived,

    /// <summary>Live in-process state observed over a control channel. Volatile and read-only by nature.</summary>
    Runtime,
}
